.TH "CandidateSearch.CandidateSearch" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CandidateSearch.CandidateSearch \- Searching for candidates using VectorSearch\&. Requires VectorSearch\&.dll v1\&.5\&.1 Requires VectorSearchCUDA\&.dll v1\&.4\&.7\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP (string[] args)"
.br
.RI "Main function that is executed when \fBCandidateSearch\fP is run\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBversion\fP = '1\&.0\&.0'"
.br
.RI "Current version of \fBCandidateSearch\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Searching for candidates using VectorSearch\&. Requires VectorSearch\&.dll v1\&.5\&.1 Requires VectorSearchCUDA\&.dll v1\&.4\&.7\&. 
.PP
Definition at line \fB10\fP of file \fBCandidateSearch\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void CandidateSearch\&.CandidateSearch\&.Main (string[] args)\fC [static]\fP"

.PP
Main function that is executed when \fBCandidateSearch\fP is run\&. 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP Arguments passed via commandline\&.
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBCandidateSearch\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string CandidateSearch\&.CandidateSearch\&.version = '1\&.0\&.0'\fC [static]\fP"

.PP
Current version of \fBCandidateSearch\fP\&. 
.PP
Definition at line \fB15\fP of file \fBCandidateSearch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
