.TH "CandidateSearch" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CandidateSearch
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCandidateSearch\fP"
.br
.RI "Searching for candidates using VectorSearch\&. Requires VectorSearch\&.dll v1\&.5\&.1 Requires VectorSearchCUDA\&.dll v1\&.4\&.7\&. "
.ti -1c
.RI "class \fBCandidateSearchCPU\fP"
.br
.RI "Searching for candidates on the CPU\&. "
.ti -1c
.RI "class \fBCandidateSearchGPU\fP"
.br
.RI "Searching for candidates on the GPU\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
