.TH "CandidateSearch.util.Peptide" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CandidateSearch.util.Peptide \- Simplified peptide class that stores peptide/peptidoform information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPeptide\fP (string Sequence, double Mass, Dictionary< int, double > Modifications, \fBSettings\fP IonSettings, bool IsDecoy)"
.br
.RI "Constructor for a new peptide/pepidoform\&. "
.ti -1c
.RI "int[] \fBgetEnconding\fP (int massRange=5000, int massMultiplier=100)"
.br
.RI "Get the encoding vector of the peptide\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Constructs a string representation of the peptide\&. "
.ti -1c
.RI "bool \fBaddModification\fP (int position, double \fBmass\fP)"
.br
.RI "Adds a modification to the peptide if the peptide isn't already modified at that position\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBsequence\fP\fC [get]\fP"
.br
.RI "Amino acid sequence of the peptide\&. "
.ti -1c
.RI "double \fBmass\fP\fC [get]\fP"
.br
.RI "Mass of the unmodified peptide\&. "
.ti -1c
.RI "Dictionary< int, double > \fBmodifications\fP\fC [get]\fP"
.br
.RI "Dictionary mapping residue positions (0 based) to modification masses\&. "
.ti -1c
.RI "bool \fBisDecoy\fP\fC [get]\fP"
.br
.RI "Is the peptide a decoy peptide or target peptide\&. "
.ti -1c
.RI "List< double > \fBions\fP\fC [get]\fP"
.br
.RI "List of theoretical ion m/z values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Simplified peptide class that stores peptide/peptidoform information\&. 
.PP
Definition at line \fB8\fP of file \fBDatabase\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CandidateSearch\&.util\&.Peptide\&.Peptide (string Sequence, double Mass, Dictionary< int, double > Modifications, \fBSettings\fP IonSettings, bool IsDecoy)"

.PP
Constructor for a new peptide/pepidoform\&. 
.PP
\fBParameters\fP
.RS 4
\fISequence\fP Sequence of amino acids\&.
.br
\fIMass\fP Mass of the unmodified peptide\&.
.br
\fIModifications\fP Dictionary that maps amino acid positions (0 based) to modification masses\&.
.br
\fIIonSettings\fP Settings used for ion calculation\&.
.br
\fIIsDecoy\fP Whether or not the peptide is a decoy peptide\&.
.RE
.PP

.PP
Definition at line \fB39\fP of file \fBDatabase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CandidateSearch\&.util\&.Peptide\&.addModification (int position, double mass)"

.PP
Adds a modification to the peptide if the peptide isn't already modified at that position\&. 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP The position (0 based) of the modification\&.
.br
\fImass\fP The modification mass\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the modification was added, false if there is already a modification on the specified residue\&.
.RE
.PP

.PP
Definition at line \fB97\fP of file \fBDatabase\&.cs\fP\&.
.SS "int[] CandidateSearch\&.util\&.Peptide\&.getEnconding (int massRange = \fC5000\fP, int massMultiplier = \fC100\fP)"

.PP
Get the encoding vector of the peptide\&. 
.PP
\fBParameters\fP
.RS 4
\fImassRange\fP Maximum m/z that should be considered while encoding\&. Has to match the specifications of VectorSearch\&.
.br
\fImassMultiplier\fP Precision of the encoding\&. Has to match the specifications of VectorSearch\&.
.RE
.PP
\fBReturns\fP
.RS 4
The encoding vector as an integer array\&.
.RE
.PP

.PP
Definition at line \fB54\fP of file \fBDatabase\&.cs\fP\&.
.SS "override string CandidateSearch\&.util\&.Peptide\&.ToString ()"

.PP
Constructs a string representation of the peptide\&. 
.PP
\fBReturns\fP
.RS 4
The string representation of the peptide\&.
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBDatabase\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<double> CandidateSearch\&.util\&.Peptide\&.ions\fC [get]\fP"

.PP
List of theoretical ion m/z values\&. 
.PP
Definition at line \fB29\fP of file \fBDatabase\&.cs\fP\&.
.SS "bool CandidateSearch\&.util\&.Peptide\&.isDecoy\fC [get]\fP"

.PP
Is the peptide a decoy peptide or target peptide\&. 
.PP
Definition at line \fB25\fP of file \fBDatabase\&.cs\fP\&.
.SS "double CandidateSearch\&.util\&.Peptide\&.mass\fC [get]\fP"

.PP
Mass of the unmodified peptide\&. 
.PP
Definition at line \fB17\fP of file \fBDatabase\&.cs\fP\&.
.SS "Dictionary<int, double> CandidateSearch\&.util\&.Peptide\&.modifications\fC [get]\fP"

.PP
Dictionary mapping residue positions (0 based) to modification masses\&. 
.PP
Definition at line \fB21\fP of file \fBDatabase\&.cs\fP\&.
.SS "string CandidateSearch\&.util\&.Peptide\&.sequence\fC [get]\fP"

.PP
Amino acid sequence of the peptide\&. 
.PP
Definition at line \fB13\fP of file \fBDatabase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
