.TH "CandidateSearch.util" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CandidateSearch.util
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDatabaseReader\fP"
.br
.RI "Reader class to read a fasta file\&. "
.ti -1c
.RI "class \fBMGFReader\fP"
.br
.RI "Reader class to read mgf files\&. "
.ti -1c
.RI "class \fBPeptide\fP"
.br
.RI "Simplified peptide class that stores peptide/peptidoform information\&. "
.ti -1c
.RI "class \fBResult\fP"
.br
.RI "Result class to transform and store the returned integer array of VectorSearch\&. "
.ti -1c
.RI "class \fBSettings\fP"
.br
.RI "Settings for digestion, ion calculation and VectorSearch\&. "
.ti -1c
.RI "class \fBSettingsReader\fP"
.br
.RI "Reader class to read a settings file\&. "
.ti -1c
.RI "class \fBSpectrum\fP"
.br
.RI "Simplified spectrum class implemention of a mass spectrum\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
