.TH "MSAMANDA_FASTAPARSER.DBPeptide" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_FASTAPARSER.DBPeptide
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDBPeptide\fP (string sequence, string sequenceOriginal, int missedCleavages, bool proteinStartFlag, \fBDBProtRef\fP protRef)"
.br
.ti -1c
.RI "int \fBCreateMD5\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBMass\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBMassInt\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSequence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBProteinStartFlag\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< \fBDBProtRef\fP > \fBDbProtRefs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSequenceOriginal\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBMissedCleavages\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBSeqHash\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB397\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_FASTAPARSER\&.DBPeptide\&.DBPeptide ()"

.PP
Definition at line \fB416\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "MSAMANDA_FASTAPARSER\&.DBPeptide\&.DBPeptide (string sequence, string sequenceOriginal, int missedCleavages, bool proteinStartFlag, \fBDBProtRef\fP protRef)"

.PP
Definition at line \fB423\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int MSAMANDA_FASTAPARSER\&.DBPeptide\&.CreateMD5 ()"

.PP
Definition at line \fB446\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBDBProtRef\fP> MSAMANDA_FASTAPARSER\&.DBPeptide\&.DbProtRefs\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB408\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "double MSAMANDA_FASTAPARSER\&.DBPeptide\&.Mass\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB400\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "int MSAMANDA_FASTAPARSER\&.DBPeptide\&.MassInt\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB402\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "int MSAMANDA_FASTAPARSER\&.DBPeptide\&.MissedCleavages\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB412\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "bool MSAMANDA_FASTAPARSER\&.DBPeptide\&.ProteinStartFlag\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB406\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "int MSAMANDA_FASTAPARSER\&.DBPeptide\&.SeqHash\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB414\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "string MSAMANDA_FASTAPARSER\&.DBPeptide\&.Sequence\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB404\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "string MSAMANDA_FASTAPARSER\&.DBPeptide\&.SequenceOriginal\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB410\fP of file \fBFASTAParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
