.TH "MSAMANDA_FASTAPARSER.ProteinDigester" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_FASTAPARSER.ProteinDigester
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProteinDigester\fP (\fBEnzyme\fP enzyme, int missedCleavages, bool useMonoisotopicMass, int minPepLength, int maxPepLength, \fBDBProtein\fP dbProtein)"
.br
.ti -1c
.RI "List< \fBDBPeptide\fP > \fBDigestProteinIntoList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB536\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_FASTAPARSER\&.ProteinDigester\&.ProteinDigester (\fBEnzyme\fP enzyme, int missedCleavages, bool useMonoisotopicMass, int minPepLength, int maxPepLength, \fBDBProtein\fP dbProtein)"

.PP
Definition at line \fB553\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "List< \fBDBPeptide\fP > MSAMANDA_FASTAPARSER\&.ProteinDigester\&.DigestProteinIntoList ()"

.PP
Definition at line \fB564\fP of file \fBFASTAParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
