.TH "MSAMANDA_IONCALCULATION.InstrumentSetting" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_IONCALCULATION.InstrumentSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstrumentSetting\fP \fBClone\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseAIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseBIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseYIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseWaterLosses\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseAmmoniaLosses\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseImmoniumIons\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseZIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseZPlusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseZPlusTwoHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseXIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseCIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseInternalFragments\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseAPlusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseAMinusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseBPlusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseBMinusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseCPlusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseCMinusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseXPlusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseXMinusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseYPlusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseYMinusHIon\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseZMinusHIon\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB968\fP of file \fBIonCalculator\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.InstrumentSetting ()"

.PP
Definition at line \fB970\fP of file \fBIonCalculator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBInstrumentSetting\fP MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.Clone ()"

.PP
Definition at line \fB998\fP of file \fBIonCalculator\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1031\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseAIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1032\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseAMinusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1047\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseAmmoniaLosses\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1036\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseAPlusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1046\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseBIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1033\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseBMinusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1049\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseBPlusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1048\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseCIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1042\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseCMinusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1051\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseCPlusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1050\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseImmoniumIons\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1037\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseInternalFragments\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1043\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseWaterLosses\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1035\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseXIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1041\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseXMinusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1053\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseXPlusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1052\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseYIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1034\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseYMinusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1055\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseYPlusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1054\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseZIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1038\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseZMinusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1056\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseZPlusHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1039\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.InstrumentSetting\&.UseZPlusTwoHIon\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB1040\fP of file \fBIonCalculator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
