.TH "MSAMANDA_IONCALCULATION.Modification" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_IONCALCULATION.Modification
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBMass\fP (bool mono)"
.br
.ti -1c
.RI "\fBModification\fP (string title, string name, double mono, double avg, char aa, bool fix, double[] neutralLosses, bool nTerminal, bool cTerminal, int id, bool protein, int maxOccurrence, bool semiFixed=false)"
.br
.ti -1c
.RI "\fBModification\fP (\fBModification\fP m)"
.br
.ti -1c
.RI "\fBModification\fP (\fBModification\fP m, bool fix, bool nTerminal, bool cTerminal, bool protein, int maxOccurrence)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetSaveString\fP (\fBModification\fP modif)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBTitle\fP"
.br
.ti -1c
.RI "readonly string \fBFullName\fP"
.br
.ti -1c
.RI "readonly char \fBAA\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double[] \fBNeutralLosses\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBNTerminal\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBCTerminal\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBProteinTerminus\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBMaxOccurrence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBID\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBFixed\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBSemiFixed\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB832\fP of file \fBIonCalculator\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_IONCALCULATION\&.Modification\&.Modification (string title, string name, double mono, double avg, char aa, bool fix, double[] neutralLosses, bool nTerminal, bool cTerminal, int id, bool protein, int maxOccurrence, bool semiFixed = \fCfalse\fP)"

.PP
Definition at line \fB855\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "MSAMANDA_IONCALCULATION\&.Modification\&.Modification (\fBModification\fP m)"

.PP
Definition at line \fB873\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "MSAMANDA_IONCALCULATION\&.Modification\&.Modification (\fBModification\fP m, bool fix, bool nTerminal, bool cTerminal, bool protein, int maxOccurrence)"

.PP
Definition at line \fB890\fP of file \fBIonCalculator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static string MSAMANDA_IONCALCULATION\&.Modification\&.GetSaveString (\fBModification\fP modif)\fC [static]\fP"

.PP
Definition at line \fB926\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "double MSAMANDA_IONCALCULATION\&.Modification\&.Mass (bool mono)"

.PP
Definition at line \fB847\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "override string MSAMANDA_IONCALCULATION\&.Modification\&.ToString ()"

.PP
Definition at line \fB907\fP of file \fBIonCalculator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly char MSAMANDA_IONCALCULATION\&.Modification\&.AA"

.PP
Definition at line \fB838\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "readonly string MSAMANDA_IONCALCULATION\&.Modification\&.FullName"

.PP
Definition at line \fB835\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "readonly string MSAMANDA_IONCALCULATION\&.Modification\&.Title"

.PP
Definition at line \fB834\fP of file \fBIonCalculator\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool MSAMANDA_IONCALCULATION\&.Modification\&.CTerminal\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB841\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.Modification\&.Fixed\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB852\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "int MSAMANDA_IONCALCULATION\&.Modification\&.ID\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB845\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "int MSAMANDA_IONCALCULATION\&.Modification\&.MaxOccurrence\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB843\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "double [] MSAMANDA_IONCALCULATION\&.Modification\&.NeutralLosses\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB839\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.Modification\&.NTerminal\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB840\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.Modification\&.ProteinTerminus\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB842\fP of file \fBIonCalculator\&.cs\fP\&.
.SS "bool MSAMANDA_IONCALCULATION\&.Modification\&.SemiFixed\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB853\fP of file \fBIonCalculator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
