.TH "MSAMANDA_FASTAPARSER.DBProtein" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_FASTAPARSER.DBProtein
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDBProtein\fP (string identifier, int id, string sequence, bool isDecoy=false)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSequence\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsDecoy\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDBProtRef\fP \fBDbProtRef\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB296\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_FASTAPARSER\&.DBProtein\&.DBProtein (string identifier, int id, string sequence, bool isDecoy = \fCfalse\fP)"

.PP
Definition at line \fB302\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDBProtRef\fP MSAMANDA_FASTAPARSER\&.DBProtein\&.DbProtRef\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB300\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "bool MSAMANDA_FASTAPARSER\&.DBProtein\&.IsDecoy\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB299\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "string MSAMANDA_FASTAPARSER\&.DBProtein\&.Sequence\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB298\fP of file \fBFASTAParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
