.TH "MSAMANDA_CHEMICALUTILS.AminoAcid" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_CHEMICALUTILS.AminoAcid
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBMass\fP (bool mono)"
.br
.ti -1c
.RI "\fBAminoAcid\fP (char oneLetter, string threeLetter, string name, double monoisotopicMass, double avgMass, double immoniumMass)"
.br
.ti -1c
.RI "\fBAminoAcid\fP (char oneLetter, string threeLetter, string name, double monoisotopicMass, double avgMass, bool mono=true)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBName\fP"
.br
.ti -1c
.RI "readonly string \fBThreeLetterCode\fP"
.br
.ti -1c
.RI "readonly char \fBOneLetterCode\fP"
.br
.ti -1c
.RI "readonly double \fBImmoniumMass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_CHEMICALUTILS\&.AminoAcid\&.AminoAcid (char oneLetter, string threeLetter, string name, double monoisotopicMass, double avgMass, double immoniumMass)"

.PP
Definition at line \fB33\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "MSAMANDA_CHEMICALUTILS\&.AminoAcid\&.AminoAcid (char oneLetter, string threeLetter, string name, double monoisotopicMass, double avgMass, bool mono = \fCtrue\fP)"

.PP
Definition at line \fB43\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double MSAMANDA_CHEMICALUTILS\&.AminoAcid\&.Mass (bool mono)"

.PP
Definition at line \fB28\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly double MSAMANDA_CHEMICALUTILS\&.AminoAcid\&.ImmoniumMass"

.PP
Definition at line \fB26\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "readonly string MSAMANDA_CHEMICALUTILS\&.AminoAcid\&.Name"

.PP
Definition at line \fB21\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "readonly char MSAMANDA_CHEMICALUTILS\&.AminoAcid\&.OneLetterCode"

.PP
Definition at line \fB23\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "readonly string MSAMANDA_CHEMICALUTILS\&.AminoAcid\&.ThreeLetterCode"

.PP
Definition at line \fB22\fP of file \fBChemicalUtils\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
