.TH "MSAMANDA_CHEMICALUTILS.ChemicalElement" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_CHEMICALUTILS.ChemicalElement
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChemicalElement\fP (string name, string fullName, double monoMass, double avgMass)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBName\fP"
.br
.ti -1c
.RI "readonly string \fBFullName\fP"
.br
.ti -1c
.RI "readonly double \fBMonoMass\fP"
.br
.ti -1c
.RI "readonly double \fBAvgMass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_CHEMICALUTILS\&.ChemicalElement\&.ChemicalElement (string name, string fullName, double monoMass, double avgMass)"

.PP
Definition at line \fB10\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly double MSAMANDA_CHEMICALUTILS\&.ChemicalElement\&.AvgMass"

.PP
Definition at line \fB8\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "readonly string MSAMANDA_CHEMICALUTILS\&.ChemicalElement\&.FullName"

.PP
Definition at line \fB6\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "readonly double MSAMANDA_CHEMICALUTILS\&.ChemicalElement\&.MonoMass"

.PP
Definition at line \fB7\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "readonly string MSAMANDA_CHEMICALUTILS\&.ChemicalElement\&.Name"

.PP
Definition at line \fB5\fP of file \fBChemicalUtils\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
