.TH "MSAMANDA_MGFPARSER.AMassCentroid" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_MGFPARSER.AMassCentroid
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAMassCentroid\fP \fBClone\fP ()"
.br
.ti -1c
.RI "\fBAMassCentroid\fP \fBClone\fP (int charge)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBPosition\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBIntensity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCharge\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBMGFParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAMassCentroid\fP MSAMANDA_MGFPARSER\&.AMassCentroid\&.Clone ()"

.PP
Definition at line \fB12\fP of file \fBMGFParser\&.cs\fP\&.
.SS "\fBAMassCentroid\fP MSAMANDA_MGFPARSER\&.AMassCentroid\&.Clone (int charge)"

.PP
Definition at line \fB17\fP of file \fBMGFParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int MSAMANDA_MGFPARSER\&.AMassCentroid\&.Charge\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB10\fP of file \fBMGFParser\&.cs\fP\&.
.SS "double MSAMANDA_MGFPARSER\&.AMassCentroid\&.Intensity\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB9\fP of file \fBMGFParser\&.cs\fP\&.
.SS "double MSAMANDA_MGFPARSER\&.AMassCentroid\&.Position\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB8\fP of file \fBMGFParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
