.TH "MSAMANDA_MGFPARSER.Spectrum" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_MGFPARSER.Spectrum
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBScanNumber\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBSpectrumId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBRT\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< \fBAMassCentroid\fP > \fBFragmentsPeaks\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< int, double > \fBImmunePeaks\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "SortedSet< double > \fBImmuneMasses\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBPrecursor\fP \fBPrecursor\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB39\fP of file \fBMGFParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_MGFPARSER\&.Spectrum\&.Spectrum ()"

.PP
Definition at line \fB49\fP of file \fBMGFParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBAMassCentroid\fP> MSAMANDA_MGFPARSER\&.Spectrum\&.FragmentsPeaks\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB44\fP of file \fBMGFParser\&.cs\fP\&.
.SS "SortedSet<double> MSAMANDA_MGFPARSER\&.Spectrum\&.ImmuneMasses\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB46\fP of file \fBMGFParser\&.cs\fP\&.
.SS "Dictionary<int, double> MSAMANDA_MGFPARSER\&.Spectrum\&.ImmunePeaks\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB45\fP of file \fBMGFParser\&.cs\fP\&.
.SS "\fBPrecursor\fP MSAMANDA_MGFPARSER\&.Spectrum\&.Precursor\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB47\fP of file \fBMGFParser\&.cs\fP\&.
.SS "double MSAMANDA_MGFPARSER\&.Spectrum\&.RT\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB43\fP of file \fBMGFParser\&.cs\fP\&.
.SS "int MSAMANDA_MGFPARSER\&.Spectrum\&.ScanNumber\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB41\fP of file \fBMGFParser\&.cs\fP\&.
.SS "int MSAMANDA_MGFPARSER\&.Spectrum\&.SpectrumId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB42\fP of file \fBMGFParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
