.TH "MSAMANDA_FASTAPARSER.DigesterDB" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_FASTAPARSER.DigesterDB
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< int, List< \fBDBPeptide\fP > > \fBDbPeptidesDictMassKey\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB965\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_FASTAPARSER\&.DigesterDB\&.DigesterDB ()"

.PP
Definition at line \fB970\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<int, List<\fBDBPeptide\fP> > MSAMANDA_FASTAPARSER\&.DigesterDB\&.DbPeptidesDictMassKey\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB968\fP of file \fBFASTAParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
