.TH "MSAMANDA_FASTAPARSER.Enzyme" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_FASTAPARSER.Enzyme
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCLEAVAGE_SPECIFICITY\fP { \fBFULL\fP, \fBSEMI\fP, \fBSEMI_N\fP, \fBSEMI_C\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCleavageSites\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCleavageInhibitors\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "CLEAVAGE_SPECIFICITY \fBSpecificity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBOffset\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Regex \fBTheRegex\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB340\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum MSAMANDA_FASTAPARSER\&.Enzyme\&.CLEAVAGE_SPECIFICITY"

.PP
Definition at line \fB351\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_FASTAPARSER\&.Enzyme\&.Enzyme ()"

.PP
Definition at line \fB342\fP of file \fBFASTAParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string MSAMANDA_FASTAPARSER\&.Enzyme\&.CleavageInhibitors\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB354\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "string MSAMANDA_FASTAPARSER\&.Enzyme\&.CleavageSites\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB353\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "string MSAMANDA_FASTAPARSER\&.Enzyme\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB357\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "int MSAMANDA_FASTAPARSER\&.Enzyme\&.Offset\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB356\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "CLEAVAGE_SPECIFICITY MSAMANDA_FASTAPARSER\&.Enzyme\&.Specificity\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB355\fP of file \fBFASTAParser\&.cs\fP\&.
.SS "Regex MSAMANDA_FASTAPARSER\&.Enzyme\&.TheRegex\fC [get]\fP"

.PP
Definition at line \fB359\fP of file \fBFASTAParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
