.TH "MSAMANDA_MGFPARSER.Precursor" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_MGFPARSER.Precursor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetMassCharge\fP (double mz, int charge, bool mono)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBMOverZ\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBUnChargedMass\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBIntensity\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBCharge\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBRank\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBMGFParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MSAMANDA_MGFPARSER\&.Precursor\&.SetMassCharge (double mz, int charge, bool mono)"

.PP
Definition at line \fB31\fP of file \fBMGFParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int MSAMANDA_MGFPARSER\&.Precursor\&.Charge\fC [get]\fP"

.PP
Definition at line \fB28\fP of file \fBMGFParser\&.cs\fP\&.
.SS "double MSAMANDA_MGFPARSER\&.Precursor\&.Intensity\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB27\fP of file \fBMGFParser\&.cs\fP\&.
.SS "double MSAMANDA_MGFPARSER\&.Precursor\&.MOverZ\fC [get]\fP"

.PP
Definition at line \fB25\fP of file \fBMGFParser\&.cs\fP\&.
.SS "int MSAMANDA_MGFPARSER\&.Precursor\&.Rank\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB29\fP of file \fBMGFParser\&.cs\fP\&.
.SS "double MSAMANDA_MGFPARSER\&.Precursor\&.UnChargedMass\fC [get]\fP"

.PP
Definition at line \fB26\fP of file \fBMGFParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
