.TH "MSAMANDA_CHEMICALUTILS.Permutations" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_CHEMICALUTILS.Permutations
.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable< Permutations >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPermutations\fP (int n, int k)"
.br
.ti -1c
.RI "\fBPermutations\fP (string key, List< int[]> elems)"
.br
.ti -1c
.RI "int[] \fBSuccessor\fP (int[] previous)"
.br
.ti -1c
.RI "void \fBCalculatePermutations\fP ()"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBPermutations\fP other)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBN\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBK\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< int[]> \fBElements\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MSAMANDA_CHEMICALUTILS\&.Permutations\&.Permutations (int n, int k)"

.PP
Definition at line \fB65\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "MSAMANDA_CHEMICALUTILS\&.Permutations\&.Permutations (string key, List< int[]> elems)"

.PP
Definition at line \fB78\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MSAMANDA_CHEMICALUTILS\&.Permutations\&.CalculatePermutations ()"

.PP
Definition at line \fB107\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "bool MSAMANDA_CHEMICALUTILS\&.Permutations\&.Equals (\fBPermutations\fP other)"

.PP
Definition at line \fB119\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "int[] MSAMANDA_CHEMICALUTILS\&.Permutations\&.Successor (int[] previous)"

.PP
Definition at line \fB86\fP of file \fBChemicalUtils\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<int[]> MSAMANDA_CHEMICALUTILS\&.Permutations\&.Elements\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB63\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "int MSAMANDA_CHEMICALUTILS\&.Permutations\&.K\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB62\fP of file \fBChemicalUtils\&.cs\fP\&.
.SS "int MSAMANDA_CHEMICALUTILS\&.Permutations\&.N\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB61\fP of file \fBChemicalUtils\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
