.TH "MSAMANDA_MGFPARSER" 3 "Version 1.0.0" "CandidateSearch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSAMANDA_MGFPARSER
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAMassCentroid\fP"
.br
.ti -1c
.RI "class \fBMGFParser\fP"
.br
.ti -1c
.RI "class \fBPrecursor\fP"
.br
.ti -1c
.RI "class \fBSpectrum\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CandidateSearch from the source code\&.
