name: Build for Ubuntu 22.04

on:
  workflow_dispatch:

jobs:
  Build-for-Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'
      - name: Build CandidateSearch
        run: |
          dotnet publish CandidateSearch.sln --runtime ubuntu.22.04-x64 --self-contained --configuration Release
      - name: Copy VectorSearch.dll to Release
        run: |
          cp dll/ubuntu_x64/VectorSearch.dll bin/Release/net6.0/ubuntu.22.04-x64
          cp dll/ubuntu_x64/VectorSearch.dll bin/Release/net6.0/ubuntu.22.04-x64/publish
      - name: Zip Release
        run: |
          cd bin/
          zip -r Release.zip Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ubuntu-22.04-x64-cpu-only
          path: bin/Release.zip
