name: Test for macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test-for-macOS:
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'
      - name: Copy test data
        run: |
          cp tests/data/* exe/macos_arm/uncompressed
      - name: Test
        run: |
          cd exe/macos_arm/uncompressed
          chmod +x CandidateSearch
          ./CandidateSearch test_spectra.mgf test_database.fasta test_settings.txt
      - name: Check result
        run: |
          head test_spectra.mgf_results.csv
