name: Test for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test-for-Windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'
      - name: Copy test data
        run: |
          copyp tests\data\* exe\windows_x64\uncompressed
      - name: Test
        run: |
          cd exe/windows_x64/uncompressed
          CandidateSearch.exe test.mgf test.fasta test.txt
      - name: Check result
        run: |
          Get-Content test.mgf_results.csv -TotalCount 10
